
version: '3'

services:
  web:
    build: .
    restart: "no"
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8010"
    container_name: movie_back
    volumes:
      - .:/movies_back
    ports:
      - "8010:8010"