# Generated by Django 4.1.7 on 2023-04-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
    ]
