# Generated by Django 4.1.7 on 2023-05-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_feed_in_world_profile_historymovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Movie'),
        ),
    ]
