# Generated by Django 4.1.7 on 2023-05-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_profile_bio_profile_birthday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSupportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('text', models.TextField()),
            ],
        ),
    ]
