# Generated by Django 4.1.7 on 2023-05-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movies.profile'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subscribers',
            field=models.ManyToManyField(related_name='group_subscribers', to='movies.profile', verbose_name='Subscribers'),
        ),
    ]
